### ISSUE TITLE
Unclear Application Period Labels

### ISSUE THREAD

**Issue by dlarocque** [bsovs/Fall2022-Internships#9]
Companies that have not began accepting applications and those who are full are both labelled as `Closed`.

It could be clearer to have companies who have not started accepting applications yet as `Not Started`.

**Comment by bsovs** [comment]
I'll move the 2021 list to a separate tab soon (once more 2022 open up) to avoid this confusion. Any other expected companies for 2022 will be added with "Not Started" tag 😄
